services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: drone_route_server
    ports:
      - "3000:3000"
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: drone_route_client
    ports:
      - "80:80"
    restart: unless-stopped
