FROM nginx:alpine

# Копируем файлы клиента
COPY drone-route-client/ /usr/share/nginx/html/

# Копируем конфигурацию Nginx
COPY drone-route-client/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
